"""CPython 3.12 struct offsets.

Generated by `tools/gen_offsets.c` via `scripts/gen_offsets.sh`.
These values are specific to the CPython version whose headers were used.
"""
import json
import os

_OFFSETS = {
    "pointer_size": 8,
    "int_size": 4,
    "RuntimeState.interpreters": 32,
    "pyinterpreters.main": 16,
    "pyinterpreters.head": 8,
    "InterpreterState.threads": 64,
    "pythreads.head": 8,
    "InterpreterState.imports": 944,
    "_import_state.modules": 0,
    "InterpreterState.interpreter_trampoline": 381736,
    "ThreadState.next": 8,
    "ThreadState.cframe": 56,
    "ThreadState.thread_id": 136,
    "ThreadState.native_thread_id": 144,
    "CFrame.current_frame": 0,
    "InterpreterFrame.f_code": 0,
    "InterpreterFrame.previous": 8,
    "InterpreterFrame.prev_instr": 56,
    "CodeObject.co_firstlineno": 68,
    "CodeObject.co_qualname": 128,
    "CodeObject.co_filename": 112,
    "CodeObject.co_name": 120,
    "CodeObject.co_linetable": 136,
    "CodeObject.co_code_adaptive": 192,
    "LongObject.long_value.lv_tag": 16,
    "LongObject.long_value.ob_digit": 24,
    "digit_size": 4,
    "Object.ob_type": 8,
    "TypeObject.tp_flags": 168,
    "TypeObject.tp_dictoffset": 288,
    "Py_TPFLAGS_MANAGED_DICT": 16,
    "HeapTypeObject.ht_cached_keys": 880,
    "DictObject.ma_keys": 32,
    "DictObject.ma_values": 40,
    "dictkeysobject_size": 32,
    "dictkeysobject.dk_log2_index_bytes": 9,
    "dictkeysobject.dk_kind": 10,
    "dictkeysobject.dk_nentries": 24,
    "PyDictKeyEntry_size": 24,
    "PyDictUnicodeEntry_size": 16,
    "BytesObject.ob_sval": 32,
    "VarObject.ob_size": 16,
    "PyASCIIObject_size": 40,
    "PyCompactUnicodeObject_size": 56,
    "PyUnicodeObject.data_any": 56,
    "_Py_CODEUNIT_size": 2,
}


def reload():
    path = os.path.join(os.path.dirname(__file__), "offsets.json")
    if os.path.exists(path):
        with open(path) as f:
            _OFFSETS.update(json.load(f))


reload()


def get(name):
    return _OFFSETS[name]
