"""CPython struct offsets — verified per-version, with fallback for unverified versions.

Verified offset tables are keyed by CPython major.minor version. For 64-bit
LP64 architectures (x86-64, aarch64) the offsets are identical for the same
CPython version, so no architecture key is needed.

At runtime, call ``configure(version_str)`` with the target process's CPython
version. If the version is unverified, a warning is printed to stderr and the
default version's offsets are used as fallback — output may be incorrect.

``offsets.json`` (generated by ``tools/gen_offsets.c`` via
``scripts/gen_offsets.sh``) serves as a development-time override: if present
alongside this module, its values override the verified table. This allows
testing newly generated offsets before promoting them to ``_VERIFIED_OFFSETS``.
"""
import json
import os
import sys

_VERIFIED_OFFSETS = {
    "3.12": {
        "pointer_size": 8,
        "int_size": 4,
        "RuntimeState.interpreters": 32,
        "pyinterpreters.main": 16,
        "pyinterpreters.head": 8,
        "InterpreterState.threads": 64,
        "pythreads.head": 8,
        "InterpreterState.imports": 944,
        "_import_state.modules": 0,
        "InterpreterState.interpreter_trampoline": 381736,
        "ThreadState.next": 8,
        "ThreadState.cframe": 56,
        "ThreadState.thread_id": 136,
        "ThreadState.native_thread_id": 144,
        "CFrame.current_frame": 0,
        "InterpreterFrame.f_code": 0,
        "InterpreterFrame.previous": 8,
        "InterpreterFrame.prev_instr": 56,
        "CodeObject.co_firstlineno": 68,
        "CodeObject.co_qualname": 128,
        "CodeObject.co_filename": 112,
        "CodeObject.co_name": 120,
        "CodeObject.co_linetable": 136,
        "CodeObject.co_code_adaptive": 192,
        "LongObject.long_value.lv_tag": 16,
        "LongObject.long_value.ob_digit": 24,
        "digit_size": 4,
        "Object.ob_type": 8,
        "TypeObject.tp_flags": 168,
        "TypeObject.tp_dictoffset": 288,
        "Py_TPFLAGS_MANAGED_DICT": 16,
        "HeapTypeObject.ht_cached_keys": 880,
        "DictObject.ma_keys": 32,
        "DictObject.ma_values": 40,
        "dictkeysobject_size": 32,
        "dictkeysobject.dk_log2_index_bytes": 9,
        "dictkeysobject.dk_kind": 10,
        "dictkeysobject.dk_nentries": 24,
        "PyDictKeyEntry_size": 24,
        "PyDictUnicodeEntry_size": 16,
        "BytesObject.ob_sval": 32,
        "VarObject.ob_size": 16,
        "PyASCIIObject_size": 40,
        "PyCompactUnicodeObject_size": 56,
        "PyUnicodeObject.data_any": 56,
        "_Py_CODEUNIT_size": 2,
    },
}

_DEFAULT_VERSION = "3.12"

_active = None


def _version_key(version_str):
    parts = version_str.split(".")
    if len(parts) >= 2:
        return f"{parts[0]}.{parts[1]}"
    return version_str


def supported_versions():
    return sorted(_VERIFIED_OFFSETS.keys())


def configure(version_str):
    global _active
    key = _version_key(version_str)
    if key in _VERIFIED_OFFSETS:
        _active = dict(_VERIFIED_OFFSETS[key])
    else:
        print(
            f"[!] Warning: CPython {version_str} is not a verified version. "
            f"Using {_DEFAULT_VERSION} offsets as fallback — output may be incorrect.",
            file=sys.stderr,
        )
        _active = dict(_VERIFIED_OFFSETS[_DEFAULT_VERSION])

    path = os.path.join(os.path.dirname(__file__), "offsets.json")
    if os.path.exists(path):
        with open(path) as f:
            _active.update(json.load(f))


def get(name):
    if _active is None:
        configure(_DEFAULT_VERSION)
    return _active[name]
