"""x86-64 syscall number/name table and argument decode metadata.

``SYSCALL_NAMES`` is generated once from
``/usr/include/x86_64-linux-gnu/asm/unistd_64.h`` and compiled in (no runtime
dependency on the header).  Only x86-64 is supported; other architectures
raise :class:`~pyprobe.errors.UnsupportedArchitecture` at engine level.

``DECODE`` describes how to render the six syscall arguments for ~50 common
syscalls (paths, buffers, flags, structs); the rest are rendered as raw hex.

Argument categories (per-argument, positional):

* ``"path"``      — NUL-terminated string read from the target (entry)
* ``"buf_in"``    — buffer whose contents are read on syscall exit
  (e.g. read(2)'s buf) — rendered ``0xaddr/"..."``
* ``"buf_out"``   — buffer written by the kernel, read on exit and rendered
  like ``buf_in``; args saved at entry because regs are clobbered on exit
* ``"open_flags"``— open/openat flags (O_RDONLY|O_CREAT|...)
* ``"mode"``      — open mode_t rendered in octal
* ``"fd"``        — plain fd (rendered as decimal)
* ``"timespec"``  — struct timespec {tv_sec, tv_nsec} read at entry
* ``"signal"``    — signal number rendered as SIGxxx
* ``"prot"``      — mmap prot flags (PROT_READ|...)
* ``"map_flags"`` — mmap flags (MAP_PRIVATE|MAP_ANONYMOUS|...)
"""

# Extracted from /usr/include/x86_64-linux-gnu/asm/unistd_64.h (x86-64).
SYSCALL_NAMES = {
    0: "read",
    1: "write",
    2: "open",
    3: "close",
    4: "stat",
    5: "fstat",
    6: "lstat",
    7: "poll",
    8: "lseek",
    9: "mmap",
    10: "mprotect",
    11: "munmap",
    12: "brk",
    13: "rt_sigaction",
    14: "rt_sigprocmask",
    15: "rt_sigreturn",
    16: "ioctl",
    17: "pread64",
    18: "pwrite64",
    19: "readv",
    20: "writev",
    21: "access",
    22: "pipe",
    23: "select",
    24: "sched_yield",
    25: "mremap",
    26: "msync",
    27: "mincore",
    28: "madvise",
    29: "shmget",
    30: "shmat",
    31: "shmctl",
    32: "dup",
    33: "dup2",
    34: "pause",
    35: "nanosleep",
    36: "getitimer",
    37: "alarm",
    38: "setitimer",
    39: "getpid",
    40: "sendfile",
    41: "socket",
    42: "connect",
    43: "accept",
    44: "sendto",
    45: "recvfrom",
    46: "sendmsg",
    47: "recvmsg",
    48: "shutdown",
    49: "bind",
    50: "listen",
    51: "getsockname",
    52: "getpeername",
    53: "socketpair",
    54: "setsockopt",
    55: "getsockopt",
    56: "clone",
    57: "fork",
    58: "vfork",
    59: "execve",
    60: "exit",
    61: "wait4",
    62: "kill",
    63: "uname",
    64: "semget",
    65: "semop",
    66: "semctl",
    67: "shmdt",
    68: "msgget",
    69: "msgsnd",
    70: "msgrcv",
    71: "msgctl",
    72: "fcntl",
    73: "flock",
    74: "fsync",
    75: "fdatasync",
    76: "truncate",
    77: "ftruncate",
    78: "getdents",
    79: "getcwd",
    80: "chdir",
    81: "fchdir",
    82: "rename",
    83: "mkdir",
    84: "rmdir",
    85: "creat",
    86: "link",
    87: "unlink",
    88: "symlink",
    89: "readlink",
    90: "chmod",
    91: "fchmod",
    92: "chown",
    93: "fchown",
    94: "lchown",
    95: "umask",
    96: "gettimeofday",
    97: "getrlimit",
    98: "getrusage",
    99: "sysinfo",
    100: "times",
    101: "ptrace",
    102: "getuid",
    103: "syslog",
    104: "getgid",
    105: "setuid",
    106: "setgid",
    107: "geteuid",
    108: "getegid",
    109: "setpgid",
    110: "getppid",
    111: "getpgrp",
    112: "setsid",
    113: "setreuid",
    114: "setregid",
    115: "getgroups",
    116: "setgroups",
    117: "setresuid",
    118: "getresuid",
    119: "setresgid",
    120: "getresgid",
    121: "getpgid",
    122: "setfsuid",
    123: "setfsgid",
    124: "getsid",
    125: "capget",
    126: "capset",
    127: "rt_sigpending",
    128: "rt_sigtimedwait",
    129: "rt_sigqueueinfo",
    130: "rt_sigsuspend",
    131: "sigaltstack",
    132: "utime",
    133: "mknod",
    134: "uselib",
    135: "personality",
    136: "ustat",
    137: "statfs",
    138: "fstatfs",
    139: "sysfs",
    140: "getpriority",
    141: "setpriority",
    142: "sched_setparam",
    143: "sched_getparam",
    144: "sched_setscheduler",
    145: "sched_getscheduler",
    146: "sched_get_priority_max",
    147: "sched_get_priority_min",
    148: "sched_rr_get_interval",
    149: "mlock",
    150: "munlock",
    151: "mlockall",
    152: "munlockall",
    153: "vhangup",
    154: "modify_ldt",
    155: "pivot_root",
    156: "_sysctl",
    157: "prctl",
    158: "arch_prctl",
    159: "adjtimex",
    160: "setrlimit",
    161: "chroot",
    162: "sync",
    163: "acct",
    164: "settimeofday",
    165: "mount",
    166: "umount2",
    167: "swapon",
    168: "swapoff",
    169: "reboot",
    170: "sethostname",
    171: "setdomainname",
    172: "iopl",
    173: "ioperm",
    174: "create_module",
    175: "init_module",
    176: "delete_module",
    177: "get_kernel_syms",
    178: "query_module",
    179: "quotactl",
    180: "nfsservctl",
    181: "getpmsg",
    182: "putpmsg",
    183: "afs_syscall",
    184: "tuxcall",
    185: "security",
    186: "gettid",
    187: "readahead",
    188: "setxattr",
    189: "lsetxattr",
    190: "fsetxattr",
    191: "getxattr",
    192: "lgetxattr",
    193: "fgetxattr",
    194: "listxattr",
    195: "llistxattr",
    196: "flistxattr",
    197: "removexattr",
    198: "lremovexattr",
    199: "fremovexattr",
    200: "tkill",
    201: "time",
    202: "futex",
    203: "sched_setaffinity",
    204: "sched_getaffinity",
    205: "set_thread_area",
    206: "io_setup",
    207: "io_destroy",
    208: "io_getevents",
    209: "io_submit",
    210: "io_cancel",
    211: "get_thread_area",
    212: "lookup_dcookie",
    213: "epoll_create",
    214: "epoll_ctl_old",
    215: "epoll_wait_old",
    216: "remap_file_pages",
    217: "getdents64",
    218: "set_tid_address",
    219: "restart_syscall",
    220: "semtimedop",
    221: "fadvise64",
    222: "timer_create",
    223: "timer_settime",
    224: "timer_gettime",
    225: "timer_getoverrun",
    226: "timer_delete",
    227: "clock_settime",
    228: "clock_gettime",
    229: "clock_getres",
    230: "clock_nanosleep",
    231: "exit_group",
    232: "epoll_wait",
    233: "epoll_ctl",
    234: "tgkill",
    235: "utimes",
    236: "vserver",
    237: "mbind",
    238: "set_mempolicy",
    239: "get_mempolicy",
    240: "mq_open",
    241: "mq_unlink",
    242: "mq_timedsend",
    243: "mq_timedreceive",
    244: "mq_notify",
    245: "mq_getsetattr",
    246: "kexec_load",
    247: "waitid",
    248: "add_key",
    249: "request_key",
    250: "keyctl",
    251: "ioprio_set",
    252: "ioprio_get",
    253: "inotify_init",
    254: "inotify_add_watch",
    255: "inotify_rm_watch",
    256: "migrate_pages",
    257: "openat",
    258: "mkdirat",
    259: "mknodat",
    260: "fchownat",
    261: "futimesat",
    262: "newfstatat",
    263: "unlinkat",
    264: "renameat",
    265: "linkat",
    266: "symlinkat",
    267: "readlinkat",
    268: "fchmodat",
    269: "faccessat",
    270: "pselect6",
    271: "ppoll",
    272: "unshare",
    273: "set_robust_list",
    274: "get_robust_list",
    275: "splice",
    276: "tee",
    277: "sync_file_range",
    278: "vmsplice",
    279: "move_pages",
    280: "utimensat",
    281: "epoll_pwait",
    282: "signalfd",
    283: "timerfd_create",
    284: "eventfd",
    285: "fallocate",
    286: "timerfd_settime",
    287: "timerfd_gettime",
    288: "accept4",
    289: "signalfd4",
    290: "eventfd2",
    291: "epoll_create1",
    292: "dup3",
    293: "pipe2",
    294: "inotify_init1",
    295: "preadv",
    296: "pwritev",
    297: "rt_tgsigqueueinfo",
    298: "perf_event_open",
    299: "recvmmsg",
    300: "fanotify_init",
    301: "fanotify_mark",
    302: "prlimit64",
    303: "name_to_handle_at",
    304: "open_by_handle_at",
    305: "clock_adjtime",
    306: "syncfs",
    307: "sendmmsg",
    308: "setns",
    309: "getcpu",
    310: "process_vm_readv",
    311: "process_vm_writev",
    312: "kcmp",
    313: "finit_module",
    314: "sched_setattr",
    315: "sched_getattr",
    316: "renameat2",
    317: "seccomp",
    318: "getrandom",
    319: "memfd_create",
    320: "kexec_file_load",
    321: "bpf",
    322: "execveat",
    323: "userfaultfd",
    324: "membarrier",
    325: "mlock2",
    326: "copy_file_range",
    327: "preadv2",
    328: "pwritev2",
    329: "pkey_mprotect",
    330: "pkey_alloc",
    331: "pkey_free",
    332: "statx",
    333: "io_pgetevents",
    334: "rseq",
    335: "uretprobe",
    424: "pidfd_send_signal",
    425: "io_uring_setup",
    426: "io_uring_enter",
    427: "io_uring_register",
    428: "open_tree",
    429: "move_mount",
    430: "fsopen",
    431: "fsconfig",
    432: "fsmount",
    433: "fspick",
    434: "pidfd_open",
    435: "clone3",
    436: "close_range",
    437: "openat2",
    438: "pidfd_getfd",
    439: "faccessat2",
    440: "process_madvise",
    441: "epoll_pwait2",
    442: "mount_setattr",
    443: "quotactl_fd",
    444: "landlock_create_ruleset",
    445: "landlock_add_rule",
    446: "landlock_restrict_self",
    447: "memfd_secret",
    448: "process_mrelease",
    449: "futex_waitv",
    450: "set_mempolicy_home_node",
    451: "cachestat",
    452: "fchmodat2",
    453: "map_shadow_stack",
    454: "futex_wake",
    455: "futex_wait",
    456: "futex_requeue",
    457: "statmount",
    458: "listmount",
    459: "lsm_get_self_attr",
    460: "lsm_set_self_attr",
    461: "lsm_list_modules",
    462: "mseal",
}

# Reverse lookup: name -> nr.
SYSCALL_NRS = {name: nr for nr, name in SYSCALL_NAMES.items()}

# ---------------------------------------------------------------------------
# Flag constants (verified against glibc x86-64 bits/mman.h & fcntl.h)
# ---------------------------------------------------------------------------

OPEN_FLAGS = {
    0x0: "O_RDONLY",
    0x1: "O_WRONLY",
    0x2: "O_RDWR",
    0x40: "O_CREAT",
    0x80: "O_EXCL",
    0x100: "O_NOCTTY",
    0x200: "O_TRUNC",
    0x400: "O_APPEND",
    0x800: "O_NONBLOCK",
    0x1000: "O_DSYNC",
    0x2000: "O_ASYNC",
    0x4000: "O_DIRECT",
    0x10000: "O_DIRECTORY",
    0x20000: "O_NOFOLLOW",
    0x40000: "O_NOATIME",
    0x80000: "O_CLOEXEC",
    0x100000: "O_SYNC",      # glibc: __O_SYNC
    0x101000: "O_SYNC",      # glibc: O_SYNC|O_DSYNC combined value
    0x200000: "O_PATH",
    0x410000: "O_TMPFILE",
}

MAP_FLAGS = {
    0x01: "MAP_SHARED",
    0x02: "MAP_PRIVATE",
    0x10: "MAP_FIXED",
    0x20: "MAP_ANONYMOUS",
    0x40: "MAP_32BIT",
    0x100: "MAP_GROWSDOWN",
    0x800: "MAP_DENYWRITE",
    0x1000: "MAP_EXECUTABLE",
    0x2000: "MAP_LOCKED",
    0x4000: "MAP_NORESERVE",
    0x8000: "MAP_POPULATE",
    0x10000: "MAP_NONBLOCK",
    0x20000: "MAP_STACK",
    0x40000: "MAP_HUGETLB",
}

PROT_FLAGS = {
    0x1: "PROT_READ",
    0x2: "PROT_WRITE",
    0x4: "PROT_EXEC",
    0x8: "PROT_SEM",
}

# ---------------------------------------------------------------------------
# DECODE: per-syscall positional argument categories (~50 common syscalls).
# Keyed by syscall name. Absent syscalls render all six args as raw hex.
# ---------------------------------------------------------------------------

DECODE = {
    "read": ["fd", "buf_in", "count"],
    "write": ["fd", "buf_in", "count"],
    "pread64": ["fd", "buf_in", "count", "offset"],
    "pwrite64": ["fd", "buf_in", "count", "offset"],
    "open": ["path", "open_flags", "mode"],
    "openat": ["dirfd", "path", "open_flags", "mode"],
    "openat2": ["dirfd", "path", "struct", "size"],
    "close": ["fd"],
    "stat": ["path", "buf_out"],
    "fstat": ["fd", "buf_out"],
    "lstat": ["path", "buf_out"],
    "newfstatat": ["dirfd", "path", "buf_out", "flags"],
    "lseek": ["fd", "offset", "whence"],
    "access": ["path", "mode"],
    "faccessat": ["dirfd", "path", "mode"],
    "faccessat2": ["dirfd", "path", "mode", "flags"],
    "unlink": ["path"],
    "unlinkat": ["dirfd", "path", "flags"],
    "rename": ["path", "path"],
    "renameat": ["dirfd", "path", "dirfd", "path"],
    "mkdir": ["path", "mode"],
    "mkdirat": ["dirfd", "path", "mode"],
    "rmdir": ["path"],
    "link": ["path", "path"],
    "symlink": ["path", "path"],
    "symlinkat": ["path", "dirfd", "path"],
    "readlink": ["path", "buf_out", "size"],
    "chmod": ["path", "mode"],
    "fchmod": ["fd", "mode"],
    "chown": ["path", "uid", "gid"],
    "fchown": ["fd", "uid", "gid"],
    "truncate": ["path", "length"],
    "ftruncate": ["fd", "length"],
    "getcwd": ["buf_out", "size"],
    "ioctl": ["fd", "request", "arg"],
    "mmap": ["addr", "length", "prot", "map_flags", "fd", "offset"],
    "mprotect": ["addr", "length", "prot"],
    "munmap": ["addr", "length"],
    "brk": ["addr"],
    "nanosleep": ["timespec", "rem"],
    "clock_nanosleep": ["clockid", "flags", "timespec", "rem"],
    "gettimeofday": ["buf_out", "tz"],
    "clock_gettime": ["clockid", "timespec_out"],
    "epoll_wait": ["epfd", "buf_out", "maxevents", "timeout"],
    "epoll_pwait": ["epfd", "buf_out", "maxevents", "timeout", "sigmask", "size"],
    "poll": ["buf_in", "nfds", "timeout"],
    "select": ["nfds", "buf_in", "buf_in", "buf_in", "timespec"],
    "socket": ["domain", "type", "protocol"],
    "connect": ["fd", "sockaddr", "addrlen"],
    "accept": ["fd", "buf_out", "buf_out"],
    "accept4": ["fd", "buf_out", "buf_out", "flags"],
    "bind": ["fd", "sockaddr", "addrlen"],
    "listen": ["fd", "backlog"],
    "sendto": ["fd", "buf_in", "len", "flags", "sockaddr", "addrlen"],
    "recvfrom": ["fd", "buf_in", "len", "flags", "sockaddr", "addrlen"],
    "sendmsg": ["fd", "msghdr", "flags"],
    "recvmsg": ["fd", "msghdr", "flags"],
    "shutdown": ["fd", "how"],
    "getsockname": ["fd", "buf_out", "buf_out"],
    "getpeername": ["fd", "buf_out", "buf_out"],
    "setsockopt": ["fd", "level", "optname", "buf_in", "optlen"],
    "getsockopt": ["fd", "level", "optname", "buf_out", "optlen"],
    "clone": ["flags", "stack", "parent_tid", "child_tid", "tls"],
    "execve": ["path", "argv", "envp"],
    "execveat": ["dirfd", "path", "argv", "envp", "flags"],
    "wait4": ["pid", "buf_out", "options", "rusage"],
    "exit": ["code"],
    "exit_group": ["code"],
    "kill": ["pid", "signal"],
    "tkill": ["tid", "signal"],
    "tgkill": ["tgid", "tid", "signal"],
    "rt_sigaction": ["signal", "act", "oldact", "size"],
    "rt_sigprocmask": ["how", "set", "oldset", "size"],
    "fcntl": ["fd", "cmd", "arg"],
    "flock": ["fd", "operation"],
    "fsync": ["fd"],
    "fdatasync": ["fd"],
    "dup": ["fd"],
    "dup2": ["oldfd", "newfd"],
    "dup3": ["oldfd", "newfd", "flags"],
    "pipe": ["buf_out"],
    "pipe2": ["buf_out", "flags"],
    "socketpair": ["domain", "type", "protocol", "buf_out"],
    "getdents64": ["fd", "buf_out", "count"],
    "epoll_create1": ["flags"],
    "epoll_ctl": ["epfd", "op", "fd", "event"],
    "eventfd2": ["count", "flags"],
    "inotify_init1": ["flags"],
    "inotify_add_watch": ["fd", "path", "mask"],
    "inotify_rm_watch": ["fd", "wd"],
    "futex": ["addr", "op", "val", "timespec", "addr2", "val3"],
    "getuid": [],
    "geteuid": [],
    "getgid": [],
    "getegid": [],
    "getpid": [],
    "getppid": [],
    "gettid": [],
}

# ---------------------------------------------------------------------------
# TRACE_GROUPS: -e trace=<group> membership (strace-style groups).
# ---------------------------------------------------------------------------

TRACE_GROUPS = {
    "file": frozenset({
        "open", "openat", "openat2", "close", "stat", "fstat", "lstat",
        "newfstatat", "lseek", "access", "faccessat", "faccessat2",
        "unlink", "unlinkat", "rename", "renameat", "renameat2", "mkdir",
        "mkdirat", "rmdir", "link", "linkat", "symlink", "symlinkat",
        "readlink", "readlinkat", "chmod", "fchmod", "fchmodat", "chown",
        "lchown", "fchown", "fchownat", "truncate", "ftruncate", "getcwd",
        "getdents64", "dup", "dup2", "dup3", "fcntl", "flock", "fsync",
        "fdatasync", "inotify_add_watch", "inotify_rm_watch",
    }),
    "network": frozenset({
        "socket", "socketpair", "connect", "accept", "accept4", "bind",
        "listen", "sendto", "recvfrom", "sendmsg", "recvmsg", "sendmmsg",
        "recvmmsg", "shutdown", "getsockname", "getpeername", "setsockopt",
        "getsockopt", "epoll_create1", "epoll_ctl", "epoll_wait",
        "epoll_pwait", "epoll_pwait2", "poll", "ppoll", "select", "pselect6",
    }),
    "process": frozenset({
        "clone", "clone3", "fork", "vfork", "execve", "execveat", "exit",
        "exit_group", "wait4", "waitid", "kill", "tkill", "tgkill",
        "rt_sigaction", "rt_sigprocmask", "set_tid_address", "set_robust_list",
        "getuid", "geteuid", "getgid", "getegid", "getpid", "getppid",
        "gettid",
    }),
    "memory": frozenset({
        "mmap", "munmap", "mprotect", "mremap", "madvise", "brk",
        "clock_nanosleep", "nanosleep", "futex",
    }),
    "signal": frozenset({
        "rt_sigaction", "rt_sigprocmask", "rt_sigreturn", "kill", "tkill",
        "tgkill",
    }),
    "desc": frozenset({
        "read", "write", "pread64", "pwrite64", "close", "fcntl", "flock",
        "ioctl", "dup", "dup2", "dup3", "pipe", "pipe2", "epoll_create1",
        "epoll_ctl", "epoll_wait", "epoll_pwait", "epoll_pwait2",
        "eventfd2", "inotify_init1", "inotify_add_watch", "inotify_rm_watch",
    }),
}
